export type Country = { code: string; name: string; flag: string };

export const COUNTRIES: Country[] = [
  { code: "IN", name: "India", flag: "🇮🇳" },
  { code: "US", name: "United States", flag: "🇺🇸" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧" },
  { code: "CA", name: "Canada", flag: "🇨🇦" },
  { code: "AU", name: "Australia", flag: "🇦🇺" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "DE", name: "Germany", flag: "🇩🇪" },
  { code: "FR", name: "France", flag: "🇫🇷" },
  { code: "IT", name: "Italy", flag: "🇮🇹" },
  { code: "ES", name: "Spain", flag: "🇪🇸" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱" },
  { code: "SG", name: "Singapore", flag: "🇸🇬" },
  { code: "JP", name: "Japan", flag: "🇯🇵" },
  { code: "BR", name: "Brazil", flag: "🇧🇷" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿" },
  { code: "MX", name: "Mexico", flag: "🇲🇽" },
];

/** Popular states / cities per country, used for the Location picker. */
export const LOCATIONS: Record<string, string[]> = {
  IN: [
    "Delhi",
    "Mumbai",
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Pune",
    "Kolkata",
    "Ahmedabad",
    "Jaipur",
    "Lucknow",
    "Surat",
    "Indore",
    "Chandigarh",
    "Kochi",
    "Nagpur",
    "Noida",
    "Gurugram",
    "Bhopal",
  ],
  US: [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "Dallas",
    "Miami",
    "Atlanta",
    "Seattle",
    "Boston",
    "Denver",
  ],
  GB: [
    "London",
    "Manchester",
    "Birmingham",
    "Leeds",
    "Glasgow",
    "Liverpool",
    "Bristol",
    "Edinburgh",
  ],
  CA: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa", "Edmonton"],
  AU: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast"],
  AE: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Ras Al Khaimah"],
  SA: ["Riyadh", "Jeddah", "Dammam", "Mecca", "Medina"],
  DE: ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne", "Stuttgart"],
  FR: ["Paris", "Lyon", "Marseille", "Toulouse", "Nice", "Bordeaux"],
  IT: ["Rome", "Milan", "Naples", "Turin", "Florence", "Bologna"],
  ES: ["Madrid", "Barcelona", "Valencia", "Seville", "Malaga", "Bilbao"],
  NL: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
  SG: ["Singapore", "Jurong", "Tampines", "Woodlands"],
  JP: ["Tokyo", "Osaka", "Kyoto", "Nagoya", "Fukuoka", "Sapporo"],
  BR: ["São Paulo", "Rio de Janeiro", "Brasília", "Belo Horizonte", "Curitiba"],
  ZA: ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth"],
  NZ: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Dunedin"],
  MX: ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Cancún"],
};

export const BUSINESS_TYPES = [
  "Restaurant / Cafe",
  "Salon & Spa",
  "Gym & Fitness",
  "Real Estate",
  "Clinic & Dental",
  "Retail Store",
  "Interior Designer",
  "Photographer",
  "Travel Agency",
  "Auto Repair",
  "Education & Coaching",
  "Construction & Contractor",
];
